---
title: "Datares1"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(tidyverse)
library(readr)
library(haven)
library(stargazer)
library(lubridate)
library(ggplot2)
read_csv("/Users/gracepanos/Desktop/youtube-new/USvideos.csv")
yt <- read_csv("/Users/gracepanos/Desktop/youtube-new/USvideos.csv")
head(yt)
y <- yt$publish_time

a <- format(as.POSIXct(y,format='%Y-%m-%d T %H:%M:%S Z'),format='%Y-%m-%d')
a

data <- mutate(yt, new_date = ydm(trending_date), new_publish_date = format(as.POSIXct(y,format='%Y-%m-%d T %H:%M:%S Z'),format='%Y-%m-%d'))
data

data$date_diff <- as.Date(as.character(data$new_date), format='%Y-%m-%d')-
                  as.Date(as.character(data$new_publish_date), format='%Y-%m-%d')

bruh <- as.numeric(data$date_diff)
hist(bruh, main = 'Histogram', xlab = 'Difference Between Trending Date minus Post Date',col = 'coral',border = 'cornsilk', xlim = c(0,35),
   breaks = 2000)

```

```{r}
read_csv("/Users/gracepanos/Desktop/youtube-new/USvideos.csv")
 ```